name: Markdown lint

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '.markdownlint-cli2.jsonc'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - '.markdownlint-cli2.jsonc'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
            !node_modules
            !**/templates/**
        continue-on-error: true
